import React, { useState } from 'react';
import { FileText, Copy, Check, Printer, Download } from 'lucide-react';

export default function Reports({ businessData }) {
  const [copied, setCopied] = useState(false);
  const { metrics, currency, topProducts, marketingChannels, recommendations } = businessData;

  const reportText = `=================================================
       EXECUTIVE BUSINESS CONSULTING REPORT
            Generated by BizConsult AI
=================================================
COMPANY:     ${businessData.title}
INDUSTRY:    ${businessData.industry}
DATE:        September 29, 2026
GROWTH GOAL: ${businessData.growthGoal}

-------------------------------------------------
1. KEY FINANCIAL PERFORMANCE METRICS
-------------------------------------------------
• Gross Revenue:       ${currency}${metrics.totalRevenue.toLocaleString()}
• Total Expenses:      ${currency}${metrics.totalExpenses.toLocaleString()}
• Net Profit:          ${currency}${metrics.netProfit.toLocaleString()}
• Net Profit Margin:   ${metrics.profitMargin}%
• MoM Sales Velocity:  +${metrics.revenueGrowth}%
• Average Order Value: ${currency}${metrics.avgOrderValue.toFixed(2)}
• Total Transactions:  ${metrics.totalOrders}

-------------------------------------------------
2. RISK & SUSTAINABILITY INDEX
-------------------------------------------------
• Overall Risk Status: ${metrics.riskLevel} (${metrics.riskScore} / 100)
• Identified Factors:
${metrics.riskFactors.map(f => `  - ${f}`).join('\n')}

-------------------------------------------------
3. MARKETING CAPITAL EFFICIENCY
-------------------------------------------------
• Total Spend:        ${currency}${metrics.marketingSpend.toLocaleString()}
• Overall Portfolio:  ${metrics.marketingRoi}x ROI
${marketingChannels.map(c => `• ${c.channel}: Spend ${currency}${c.spend.toLocaleString()} -> Rev ${currency}${c.revenue.toLocaleString()} (CAC ${currency}${c.cac})`).join('\n')}

-------------------------------------------------
4. PRIORITIZED STRATEGIC RECOMMENDATIONS
-------------------------------------------------
${recommendations.map((r, i) => `[Action #${i + 1}] ${r.title}
Category:   ${r.category} | Impact: ${r.impact} | Effort: ${r.effort}
Projected:  ${r.estimatedImpact}
Rationale:  ${r.description}
Status:     ${r.status}`).join('\n\n')}

=================================================
CONFIDENTIAL & PROPRIETARY — BIZCONSULT AI
=================================================`;

  const handleCopy = () => {
    navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6 pb-12">
      {/* Header & Actions */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 bg-slate-800/60 border border-slate-750 p-6 rounded-2xl">
        <div className="flex items-center space-x-3">
          <div className="p-2.5 rounded-xl bg-sky-500/10 text-sky-400">
            <FileText className="w-5 h-5" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-white">Executive Business Summary</h2>
            <p className="text-xs text-slate-400">Board-level diagnostic export suitable for investors, advisors, and team leads</p>
          </div>
        </div>

        <div className="flex items-center space-x-2">
          <button
            onClick={handleCopy}
            className="flex items-center space-x-1.5 bg-slate-700 hover:bg-slate-650 text-slate-200 text-xs font-bold px-3.5 py-2 rounded-xl transition-colors border border-slate-600"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
            <span>{copied ? 'Copied!' : 'Copy Text'}</span>
          </button>
          <button
            onClick={handlePrint}
            className="flex items-center space-x-1.5 bg-sky-600 hover:bg-sky-500 text-white text-xs font-bold px-3.5 py-2 rounded-xl transition-colors shadow-sm"
          >
            <Printer className="w-4 h-4" />
            <span>Print / PDF</span>
          </button>
        </div>
      </div>

      {/* Formatted Report Card */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 sm:p-8 font-mono text-xs text-slate-300 leading-relaxed shadow-lg overflow-x-auto whitespace-pre">
        {reportText}
      </div>
    </div>
  );
}
